id: I4068ACB4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T05:34:27+00:00'
last_modified: '2022-06-07T16:59:02.794847+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20284
  title: གེ་སར་སྒྲུང་གི་རིག་གཞུང་དཔེ་དེབ ༼༢༠༡༤༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    780D:
      image_group_id: I8LS20286
      title: ''
      total_pages: 293
      order: 1
      base_file: 780D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
