id: P003010
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20284
  title: གེ་སར་སྒྲུང་གི་རིག་གཞུང་དཔེ་དེབ ༼༢༠༡༤༽
  author: ''
  volumes:
    4d96d6d690be4bf19da45dccd3d59918:
      image_group_id: I8LS20286
      title: ''
      volume_number: 1
      total_pages: 293
      base_file: v001.txt
